### ISSUE TITLE
when I execute 'npm run dev' ,there is lots of error 

### ISSUE THREAD

**Issue by doublenian** [appcomponents/material-components#2]
I have `npm install ` and run `npm run dev` ,There is lot of error, when I review it,it seems about synax error and file missing,Can you help me. and another problem, you have missing compile the to `dist/material-components` and just compile the `docs` 
```
`ERROR in /Users/doublenian/test/material-components/src/directives/bind-raw/index.ts
(3,5): error TS2322: Type '{ [x: string]: number | ((value: any) => void); priority: number; bind: () => void; update: (valu...' is not assignable to type 'DirectiveOption'.
  Types of property 'priority' are incompatible.
    Type 'number' is not assignable to type 'boolean'.

ERROR in /Users/doublenian/test/material-components/src/directives/bind-boolean/index.ts
(4,5): error TS2322: Type '{ [x: string]: number | ((value: any) => void); priority: number; update: (value: any) => void; }' is not assignable to type 'DirectiveOption'.
  Types of property 'priority' are incompatible.
    Type 'number' is not assignable to type 'boolean'.

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./mapping in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 7:14-34

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./doc-app in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 8:10-30

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../components in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 9:19-43 12:19-43

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../directives in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 10:19-43

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../mixins in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 11:15-35

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./logo/vue in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 13:12-33

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./logo/materialize in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 14:20-49

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./doc-api in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 15:16-36

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./doc-sources in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 16:20-44

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./snippet in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 17:16-36

ERROR in ./src/docs/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./doc-tabs in /Users/doublenian/test/material-components/src/docs
 @ ./src/docs/index.ts 18:17-38

ERROR in dlopen(/Users/doublenian/test/material-components/node_modules/node-sass/vendor/darwin-x64-47/binding.node, 1): no suitable image found.  Did find:
	/Users/doublenian/test/material-components/node_modules/node-sass/vendor/darwin-x64-47/binding.node: truncated mach-o error: segment __TEXT extends to 1167360 which is past end of file 295472
 @ ./src/docs/doc-main.scss 4:14-175

ERROR in ./src/docs/doc-main.scss
Module build failed: Error: dlopen(/Users/doublenian/test/material-components/node_modules/node-sass/vendor/darwin-x64-47/binding.node, 1): no suitable image found.  Did find:
	/Users/doublenian/test/material-components/node_modules/node-sass/vendor/darwin-x64-47/binding.node: truncated mach-o error: segment __TEXT extends to 1167360 which is past end of file 295472
    at Error (native)
    at Object.Module._extensions..node (module.js:423:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/doublenian/test/material-components/node_modules/node-sass/lib/index.js:16:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/doublenian/test/material-components/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at DependenciesBlock.loadPitch (/Users/doublenian/test/material-components/node_modules/webpack-core/lib/NormalModuleMixin.js:193:17)
    at DependenciesBlock.loadPitch (/Users/doublenian/test/material-components/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at DependenciesBlock.loadPitch (/Users/doublenian/test/material-components/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at DependenciesBlock.loadPitch (/Users/doublenian/test/material-components/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at DependenciesBlock.loadPitch (/Users/doublenian/test/material-components/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at DependenciesBlock.doBuild (/Users/doublenian/test/material-components/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/Users/doublenian/test/material-components/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/Users/doublenian/test/material-components/node_modules/webpack/lib/Compilation.js:126:9)
    at Compilation.<anonymous> (/Users/doublenian/test/material-components/node_modules/webpack/lib/Compilation.js:398:8)
    at /Users/doublenian/test/material-components/node_modules/webpack/lib/NormalModuleFactory.js:58:13
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in dlopen(/Users/doublenian/test/material-components/node_modules/node-sass/vendor/darwin-x64-47/binding.node, 1): no suitable image found.  Did find:
    	/Users/doublenian/test/material-components/node_modules/node-sass/vendor/darwin-x64-47/binding.node: truncated mach-o error: segment __TEXT extends to 1167360 which is past end of file 295472`

```

**Comment by mjanys** [comment]
Hi,

run npm install for download all dependencies before. I think it could help.

Script tasks are:
dist: compile components, bundle, minimalize to dist directory
docs: compile components + docs, bundle to docs directory
dev is same as docs with watch parameter, it means dev task is design for development of components.
So when you want to make change, you can just compile by dist, when you want to do more changes run dev, open index.html and try components in examples in doc, after that it is time for run the dist task

Let me know how it works

**Comment by mjanys** [comment]
I confirm issue, this was hide from me because  IDE. I will fix it

**Comment by doublenian** [comment]
Thanks , I will be waitting online 😃

**Comment by mjanys** [comment]
Okey, there was two problems,

first is vue-class-components has priority as boolean (https://github.com/vuejs/vue-class-component/blob/master/index.d.ts#L24) but it is number in Vue API. I maked directives with type any.

There was also problem with depenenecy velocity-animate and I added it as dependency.

I have just pushed fix :). Rerun npm install and try it again

There is explaination of run-script tasks:

dist: compile components, bundle to dist folder and minify to dist folder
docs: compile components, compile docs, bundle to docs folder
dev: is docs task with watch parameter for development

So when you want to do just a few changes run dist. When you want do more changes run dev, open index.html and you can try you changes on examples in docs. After you are finished run dist task.

**Comment by doublenian** [comment]
when I run `npm run dist`, there is error
```
ERROR in ./src/components/library.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../components in /Users/doublenian/test/material-components/src/components
 @ ./src/components/library.ts 2:19-43

ERROR in ./src/components/library.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../directives in /Users/doublenian/test/material-components/src/components
 @ ./src/components/library.ts 3:19-43

ERROR in ./src/components/library.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../mixins in /Users/doublenian/test/material-components/src/components
 @ ./src/components/library.ts 4:15-35
```

**Comment by mjanys** [comment]
Right sequence for build is:

npm install (once)
npm run-script dist

because project is build with webpack not npm directly

**Comment by mjanys** [comment]
Update your master once more please, I had some problem with push maybe (maybe not) Just for sure

**Comment by mjanys** [comment]
I se see that npm run dist is same as run-script dist ... but unfortunately it works for me

**Comment by doublenian** [comment]
I execute the commands above ,but same error
```
➜  material-components git:(master) npm install
➜  material-components git:(master) npm run-script dist

> vue-material-components@0.0.1 dist /Users/doublenian/test/material-components
> webpack --colors --progress --config  webpack.build.js --env dist && minify --output dist/vue-material-components.min.js dist/vue-material-components.js

 10% 0/1 build modulests-loader: Using typescript@1.8.9 and /Users/doublenian/test/material-components/tsconfig.json
Hash: c288ab17a6efa568dd24
Version: webpack 1.12.14
Time: 3755ms
                            Asset     Size  Chunks             Chunk Names
./dist/vue-material-components.js  3.25 kB       0  [emitted]  main
    + 2 hidden modules

ERROR in ./src/components/library.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../components in /Users/doublenian/test/material-components/src/components
 @ ./src/components/library.ts 2:19-43

ERROR in ./src/components/library.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../directives in /Users/doublenian/test/material-components/src/components
 @ ./src/components/library.ts 3:19-43

ERROR in ./src/components/library.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../mixins in /Users/doublenian/test/material-components/src/components
 @ ./src/components/library.ts 4:15-35
Minification complete
➜  material-components git:(master) ✗ git branch
  gh-pages
* master
➜  material-components git:(master) ✗
```

**Comment by mjanys** [comment]
Everything looks ok, but I use Windows. Please try resolve it yourself :(, and let me know,

I might start with
```
resolve: {
        root: path.resolve('./')
    },
```
or 
```
loaders: [{
      test: /\.ts$/,
      include: [
        path.resolve('./src')
      ],
      loader: 'ts'
    },
```
in webpack.config.js

try different paths etc.

**Comment by mjanys** [comment]
Any update?

**Comment by mjanys** [comment]
duplicates https://github.com/appcomponents/material-components/issues/4
